manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: carrefinho                           
      url-base: https://github.com/carrefinho     
      
  projects:
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main

    - name: zmk-split-peripheral-input-relay
      remote: badjeff
      revision: main

    - name: zmk
      remote: zmkfirmware
      revision: feat/pointers-with-input-processors
      import: app/west.yml

    - name: zmk-input-behavior-listener
      remote: badjeff
      revision: main

    - name: prospector-zmk-module                
      remote: carrefinho                         
      revision: main                            
      
  self:
    path: config
